from __future__ import annotations

from ajax_terminal.charts.theme import (
    AJAX_BACKGROUND,
    AJAX_BORDER,
    AJAX_MUTED,
    AJAX_TEXT,
    VOL_SURFACE_COLORS,
)

SCENE_BACKGROUND = "#181b1e"
GRID_COLOR = "#747b81"
GRID_MINOR = "#4d555b"
LABEL_COLOR = AJAX_TEXT
MUTED_LABEL_COLOR = AJAX_MUTED
SURFACE_EDGE = "#1d3821"
SURFACE_COLORS = VOL_SURFACE_COLORS
FRAME_COLOR = AJAX_BORDER
APP_BACKGROUND = AJAX_BACKGROUND
